apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: golang-role
rules:
- apiGroups: [""]
  resources: ["pods","configmaps","namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: golang-role-binding
  namespace: default
roleRef:
  kind: ClusterRole
  name: golang-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: golang-sa
  namespace: default